### ISSUE TITLE
有关不能消除隐式ε

### ISSUE THREAD

**Issue by AWeng0526** [Wwqf/Parsing#1]
eliminateImmediateLeftRecursion的注释提及了
> bug - 不能消除隐式ε(替换后存在的ε)

请问能给出一个实例吗

**Comment by Wwqf** [comment]
假设给出文法：
>S -> S A c | d
A -> a c | ε

由代码生成的左递归消除：
> S -> d S`

> A -> a c | ε 

> S` -> A c S` | ε

当时好像是这种情况, 即 A中存在一个能推导出ε的产生式；刚刚经过试验和查看书上说明，这种消除得出的结果不一定是正确的，但结果是无害的。

**Comment by AWeng0526** [comment]
感谢!
